FROM alpine:3.20

RUN apk add --no-cache \
    bash \
    bind-tools \
    bridge-utils \
    busybox-extras \
    curl \
    iperf3 \
    iptables \
    iproute2 \
    iputils \
    jq \
    mtr \
    net-tools \
    nmap-ncat \
    openssh-client \
    tcpdump \
    traceroute \
    wget

CMD ["sh"]
